site_name: hudoc
theme: 
  name: material
  features:
    - content.code.copy
    - navigation.sections
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
docs_dir: docs
nav:
  - Home: index.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
